name: Release Tauri App (macOS, Windows, Linux)

on:
  push:
    tags:
      - "v*"    # Runs when you push a tag like v1.0.0
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app
        run: npm run tauri build

      - name: Prepare artifacts
        id: prep
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" == "Linux" ]; then
            cp src-tauri/target/release/bundle/appimage/*.AppImage dist/ || true
            cp src-tauri/target/release/bundle/deb/*.deb dist/ || true
          elif [ "${{ runner.os }}" == "Windows" ]; then
            cp src-tauri/target/release/bundle/msi/*.msi dist/ || true
            cp src-tauri/target/release/bundle/nsis/*.exe dist/ || true
          else
            cp src-tauri/target/release/bundle/dmg/*.dmg dist/ || true
            cp -R src-tauri/target/release/bundle/macos/*.app dist/ || true
          fi
          echo "files=$(ls dist | xargs)" >> $GITHUB_OUTPUT

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
